
apiVersion: v1
kind: Service
metadata:
  name: devops-application-service
  namespace: default
  labels:
    app: devops-application
spec:
  selector:
    app: devops-application
  ports:
    - port: 8080   # Service'in dinleyeceği port
      targetPort: 8080   # Pod içindeki .jar uygulamanın portu - containerPort ile aynı olmalı
  type: LoadBalancer    # Service tipi (ClusterIP, NodePort, LoadBalancer, vb.)